DROP PROCEDURE IF EXISTS insert_employee; 

DELIMITER //

CREATE PROCEDURE insert_employee(
	IN E_ID INT, 
	IN FIRST_NAME VARCHAR(20), 
	IN LAST_NAME VARCHAR(20), 
	IN DEPARTMENTID INT
)
BEGIN
    INSERT INTO employee(ID, FIRSTNAME, LASTNAME, DEPARTMENT_ID) 
    VALUES (E_ID, FIRST_NAME, LAST_NAME, DEPARTMENTID);
END //

DELIMITER ;

CALL insert_employee(3, 'F3', 'L3', 1);