DROP PROCEDURE IF EXISTS update_employee; 

DELIMITER //

CREATE PROCEDURE update_employee(IN E_ID INT, 
	IN FIRST_NAME VARCHAR(20), 
	IN LAST_NAME VARCHAR(20), 
	IN DEPARTMENTID INT)
BEGIN
    UPDATE Employee 
    SET FIRSTNAME = FIRST_NAME, LASTNAME = LAST_NAME, DEPARTMENT_ID = DEPARTMENTID 
    WHERE ID = E_ID;
END //

DELIMITER ;

CALL update_employee(4, 'F44', 'L44', 1);
