CREATE TABLE EMPLOYEE (
    EMPID INT PRIMARY KEY,
    EMP_NAME VARCHAR(20) NOT NULL,
    DEPT VARCHAR(20),
    SALARY INT NOT NULL,
    DOJ DATE NOT NULL,
    BRANCH VARCHAR(20) NOT NULL
);

insert INTO EMPLOYEE
VALUES(101,'AMIT','PRODUCTION',45000,'2000-03-12','BANGLORE');
insert INTO EMPLOYEE
VALUES(102,'RAKESH','HR',70000,'2002-07-03','BANGLORE');
insert INTO EMPLOYEE
VALUES(103,'RAMESH','MANAGER',120000,'2001-01-11','MYSORE');
insert INTO EMPLOYEE
VALUES(105,'SUNITA','IT',67000,'2001-08-01','MYSORE');
insert INTO EMPLOYEE
VALUES(106,'RAJIV','CIVIL',145000,'2003-09-20','MUMBAI');

SELECT 
    *
FROM
    EMPLOYEE;

SELECT 
    EMP_NAME, SALARY
FROM
    EMPLOYEE;

SELECT 
    AVG(salary)
FROM
    EMPLOYEE;

SELECT 
    COUNT(*)
FROM
    EMPLOYEE;
 
SELECT 
    COUNT(DISTINCT emp_name)
FROM
    EMPLOYEE;
    
SELECT 
    EMP_NAME, SUM(SALARY), COUNT(*)
FROM
    EMPLOYEE
GROUP BY (EMP_NAME);
    
SELECT 
    EMP_NAME, SUM(SALARY)
FROM
    EMPLOYEE
GROUP BY (EMP_NAME)
HAVING SUM(SALARY) > 120000;

SELECT 
    emp_name
FROM
    EMPLOYEE
ORDER BY emp_name DESC;

SELECT 
    *
FROM
    EMPLOYEE
WHERE
    emp_name = 'Amit' AND salary > 50000;
